### ISSUE TITLE
Create .netstandard nuget package.

### ISSUE THREAD

**Issue by ngbrown** [nhibernate/iesi.collections#2]
Wouldn't need be a very high version of .netstandard.  Probably 1.0.

**Comment by fredericDelaporte** [comment]
Is this for standalone usage or forecasting the need for NHibernate .Net Core version? If it is the latter, this [PR](https://github.com/nhibernate/nhibernate-core/pull/604) wants to go the other way round, removing the explicit dependency (thus dropping a feature by the way for .Net Core, unless this issue gets done).

**Comment by fredericDelaporte** [comment]
By the way, Iesi has its [Jira project](https://nhibernate.jira.com/projects/IES/issues/IES-1?filter=allissues). Now we have one issue here and another one there. We should choose only one tracking tool, and disable the other.

**Comment by fredericDelaporte** [comment]
Ported as [IES-5](https://nhibernate.jira.com/browse/IES-5), I am disabling issues here on Github (will go 404).

**Comment by hazzik** [comment]
@fredericDelaporte the JIRA for Iesi has been deprecated (and It's also closed for new issues).

**Comment by fredericDelaporte** [comment]
Ok, I have not seen it was having the "Archived" scheme on Jira. Putting "deprecated" in title as you have just done is a good idea. I delete my previous comment for removing that noise.

What about Proxy Generator? It has not the archived scheme on Jira while having an empty issue tracking on GitHub. Same for Spatial but with issues on both sides.

**Comment by hazzik** [comment]
They need to be sorted out. The issues for spatial need to be moved across to Github, as a complete separate team has picked up spatial project.

For proxy generator the same. 

I'll deal with both later.

**Comment by ngbrown** [comment]
@fredericDelaporte yes, it's for the NHibernate .netstandard version.  `iesi.collections` is still required for the `order-by` option of a `set` mapping.

I don't necessarily agree with having stuff dynamically load, especially with NuGet's dependency management being available, so I hope to just keep `iesi.collections` along for the ride as long as it's used.

**Comment by hazzik** [comment]
>Wouldn't need be a very high version of .netstandard. Probably 1.0.

~netstandard 1.0 does not have `ISet<>`~ My bad. It does have it.
