### ISSUE TITLE
NuGet package contains debug build assemblies

### ISSUE THREAD

**Issue by cremor** [nhibernate/iesi.collections#6]
The NuGet package of version 4.0.2 contains debug build assemblies. This is a new problem in version 4.0.2, the package with version 4.0.1.4000 was fine.

This also affects the NHiberante binary downloads from Sourceforge. 4.1.1.GA still had the release build Iesi.Collections.dll but starting with 5.0.0 it contains the debug build.

**Comment by fredericDelaporte** [comment]
Indeed. The `GaRelease.bat` generates a NuGet with release assemblies but the TeamCity build generates a NuGet with debug assemblies.

@hazzik, in such case, should we generate a new version of the NuGet package, or replace the previous one with a fixed one?

**Comment by fredericDelaporte** [comment]
I have changed the TeamCity configuration for having it building in release instead. I guess previous publications were done from the `GaRelease.bat` locally generated package instead of doing them from TeamCity artifacts.

**Comment by fredericDelaporte** [comment]
The [new build](https://teamcity.jetbrains.com/viewLog.html?buildId=1266470&tab=buildResultsDiv&buildTypeId=bt923) has now its artifacts built in release mode.
So now either we override previous package with the one from this build, or we increment version, wait for the build and push a new one.

**Comment by cremor** [comment]
I wouldn't replace the existing package. If you do that every user has to explicitly delete the local package to get the fixed version. And that might not even be possible, e.g. on a build server where you don't have access to the local package cache.

**Comment by hazzik** [comment]
Packages on NuGet are immutable, so not possible to “replace”

**Comment by fredericDelaporte** [comment]
4.0.3 is now pushed on NuGet, waiting their automated indexation.
