### ISSUE TITLE
Please update the FileVersion when updating the ProductVersion or AssemblyVersion

### ISSUE THREAD

**Issue by tomtrias** [nhibernate/iesi.collections#9]
If the `FileVersion` doesn't get bumped, the MSI installation of the Iesi.Collections.dll breaks down.

**Comment by oskarb** [comment]
To be clear - FileVersion should ALWAYS be updated when the file is modified. ProductVersion and AssemblyVersion only sometimes.

**Comment by tomtrias** [comment]
Agreed.
